### ISSUE TITLE
Froge Port Checklist

### ISSUE THREAD

**Issue by ThePlasticPotato** [ValkyrienSkies/Clockwork#29]
- [x] Game Launches
- [x] World Loads
- [x] Create mixins not fucked:tm:
- [x] Propellor works
- [x] Propellor provides thrust
- [x] Propellor stream works
- [x] Infuser works
- [x] Infuser animates correctly
- [x] Infuser infuses correctly
- [x] Bluperglue works
- [x] Gravitron works
- [x] Gravitron grabs correctly
- [x] Flap Bearing works
- [x] Flap Bearing flaps correctly
- [x] Library files work/are organized
- [x] Game runs out of dev
- [x] Job done
